name: plot_file
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0-266.1.beta <3.0.0'

dependencies:
  evaluator:
    path: ../evaluator
  expressions:
    path: ../expressions
  math_functions:
    path: ../math_functions

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
